### ISSUE TITLE
Please update README after latest updates

### ISSUE THREAD

**Issue by demogorgorn** [florent37/MyLittleCanvas#3]
Hello! Thank you for the library! It's amazing and very useful. Can you please update README after latest updates? I think for new users it will be very useful.

Thanks!

**Comment by florent37** [comment]
I'm currently working on this lib, I will rework the README from 0 :)

2018-03-29 8:05 GMT+02:00 Oleg Martemjanov <notifications@github.com>:

**Comment by demogorgorn** [comment]
Thanks for quick reply and for ALL your work!

**Comment by florent37** [comment]
but you can sen me some feature you would like in the README,
I thinked about showing some components made with MyLittleCanvas, and a
link to their implementation

Then the list of all "shapes" and their configuration

Then How to animate

2018-03-29 8:16 GMT+02:00 Oleg Martemjanov <notifications@github.com>:

**Comment by SaravananOffl** [comment]
Add current version also in the README! It would be useful.   

` compile 'com.github.florent37:mylittlecanvas:(lastversion)`

It would be **easy for viewers** to navigate

**Comment by florent37** [comment]
but the version is always shown above

2018-03-31 6:46 GMT+02:00 Saravanan G <notifications@github.com>:
